[project]
name = 'Decentralized-Warehouse-Inventory-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.facility-verification]
path = 'contracts/facility-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.regulatory-requirement]
path = 'contracts/regulatory-requirement.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
